### ISSUE TITLE
本地运行不起来

### ISSUE THREAD

**Issue by Super-jie6** [hu-snail/vue3-admin-element-template#1]
![image](https://user-images.githubusercontent.com/58161070/139412121-d4d7209d-c0fe-4bd9-95ad-200b2f0619fa.png)

**Comment by hu-snail** [comment]
关闭 重新运行 npm run serve 试试，正在修改改这个问题

**Comment by Super-jie6** [comment]
> 关闭 重新运行 npm run serve 试试，正在修改改这个问题

试过了，还是不行

**Comment by Super-jie6** [comment]
> 关闭 重新运行 npm run serve 试试，正在修改改这个问题

能不能快点解决啊😂

**Comment by hu-snail** [comment]
已修复
