### ISSUE TITLE
commitlint.config.js 文件名最后有空格，无法clone

### ISSUE THREAD

**Issue by shaojunliang** [hu-snail/vue3-admin-element-template#2]
error: invalid path 'commitlint.config.js '
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by neilbowman666** [comment]
+1，恼火

**Comment by fuquanli** [comment]
+1，下载zip文件后也没办法本地运行。

**Comment by hu-snail** [comment]
已修复
